package emlakceptePatternMain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import emlakceptePattern.model.RealtyOption;
import emlakceptePattern.model.RealtyStatus;
import emlakceptePattern.model.RealtyType;
import emlakceptePattern.model.Realty;
import emlakceptePattern.model.User;
import emlakceptePattern.model.UserType;
import emlakceptePattern.service.RealtyService;
import emlakceptePattern.service.UserService;

public class Main {

	public static void main(String[] args) 
	{
		//Factory object
		Factory factory = new Factory();
		
		
		//Test users generated by Factory
		User userbilge = factory.getUser();
		
		userbilge.setName("Bilge");
		userbilge.setMail("bilgekaganbr@gmail.com");
		userbilge.setPassword("123456");
		userbilge.setCreateDate(LocalDateTime.now());
		userbilge.setType(UserType.INDIVIDUAL);
		userbilge.setRealtyList(Collections.emptyList());
		userbilge.setFavoriteRealtyList(Collections.emptyList());
		userbilge.setSavedRealtyList(Collections.emptyList());
		userbilge.setMessages(Collections.emptyList());
		
		User usercem = factory.getUser();
		
		usercem.setName("Cem");
		usercem.setMail("cemdrman@gmail.com");
		usercem.setPassword("351264");
		usercem.setCreateDate(LocalDateTime.now());
		usercem.setType(UserType.CORPORATE);
		usercem.setRealtyList(Collections.emptyList());
		usercem.setFavoriteRealtyList(Collections.emptyList());
		usercem.setSavedRealtyList(Collections.emptyList());
		usercem.setMessages(Collections.emptyList());
		
		User userfisun = factory.getUser();
		
		userfisun.setName("Fisun");
		userfisun.setMail("fisunbrk@gmail.com");
		userfisun.setPassword("354261");
		userfisun.setCreateDate(LocalDateTime.now());
		userfisun.setType(UserType.INDIVIDUAL);
		userfisun.setRealtyList(Collections.emptyList());
		userfisun.setFavoriteRealtyList(Collections.emptyList());
		userfisun.setSavedRealtyList(Collections.emptyList());
		userfisun.setMessages(Collections.emptyList());
		
		
		User userahmet = factory.getUser();
		
		userahmet.setName("Ahmet");
		userahmet.setMail("ahmet@gmail.com");
		userahmet.setPassword("423");
		userahmet.setCreateDate(LocalDateTime.now());
		userahmet.setType(UserType.INDIVIDUAL);
		userahmet.setRealtyList(Collections.emptyList());
		userahmet.setFavoriteRealtyList(Collections.emptyList());
		userahmet.setSavedRealtyList(Collections.emptyList());
		userahmet.setMessages(Collections.emptyList());
		
		User userayse = factory.getUser();
		
		userayse.setName("Ayşe");
		userayse.setMail("ayse.gmail.com");
		userayse.setPassword("514263");
		userayse.setCreateDate(LocalDateTime.now());
		userayse.setType(UserType.INDIVIDUAL);
		userayse.setRealtyList(Collections.emptyList());
		userayse.setFavoriteRealtyList(Collections.emptyList());
		userayse.setSavedRealtyList(Collections.emptyList());
		userayse.setMessages(Collections.emptyList());
		
		User usermehmet = factory.getUser();
		
		usermehmet.setName("Mehmet");
		usermehmet.setMail("mehmet@gmail.co");
		usermehmet.setPassword("435261");
		usermehmet.setCreateDate(LocalDateTime.now());
		usermehmet.setType(UserType.INDIVIDUAL);
		usermehmet.setRealtyList(Collections.emptyList());
		usermehmet.setFavoriteRealtyList(Collections.emptyList());
		usermehmet.setSavedRealtyList(Collections.emptyList());
		usermehmet.setMessages(Collections.emptyList());
		
		
		//Test realty generated by Factory
		
		Realty realty1 = factory.getRealty();
		
		realty1.setNo(1673542);
		realty1.setTitle("BEYLİKDÜZÜ BAŞKENT YAPI'DAN METROBÜSE 8DK ŞIK TASARIMLI 2+1");
		realty1.setPublishedDate(LocalDateTime.now());
		realty1.setUser(userbilge);
		realty1.setStatus(RealtyStatus.ACTIVE);
		realty1.setType(RealtyType.HOUSE);
		realty1.setOption(RealtyOption.FORSALE);
		realty1.setProvince("İstanbul");
		realty1.setDistrict("Beylikdüzü");
		
		Realty realty2 = factory.getRealty();
		
		realty2.setNo(2531476);
		realty2.setTitle("YOO İSTANBUL SATIŞ OFİSİNDEN KİRALIK BÜYÜK BAHÇE DUBLEKSİ 495 m2");
		realty2.setPublishedDate(LocalDateTime.now());
		realty2.setUser(userfisun);
		realty2.setStatus(RealtyStatus.ACTIVE);
		realty2.setType(RealtyType.HOUSE);
		realty2.setOption(RealtyOption.FORRENT);
		realty2.setProvince("İstanbul");
		realty2.setDistrict("Beşiktaş");
		
		Realty realty3 = factory.getRealty();
		
		realty3.setNo(2316517);
		realty3.setTitle("YOO İSTANBUL SATIŞ OFİSİNDEN BOĞAZ MANZARALI KİRALIK BAHÇE KATI 3,5+1 228 m2");
		realty3.setPublishedDate(LocalDateTime.now());
		realty3.setUser(userbilge);
		realty3.setStatus(RealtyStatus.ACTIVE);
		realty3.setType(RealtyType.HOUSE);
		realty3.setOption(RealtyOption.FORRENT);
		realty3.setProvince("İstanbul");
		realty3.setDistrict("Beşiktaş");
		
		Realty realty4 = factory.getRealty();
		
		realty4.setNo(7425136);
		realty4.setTitle("MSY'DEN BULVAR'DA 5.5+1 250m2 NET FULL YAPILI SAUNALI HAMAMLI");
		realty4.setPublishedDate(LocalDateTime.now());
		realty4.setUser(userfisun);
		realty4.setStatus(RealtyStatus.ACTIVE);
		realty4.setType(RealtyType.HOUSE);
		realty4.setOption(RealtyOption.FORSALE);
		realty4.setProvince("Ankara");
		realty4.setDistrict("Keçiören");
		
		/*Realty realty5 = factory.getRealty();
		
		realty5.setNo(1367524);
		realty5.setTitle("İstanbul , Fulya da Merkezi Konumda SATILIK MİNİ PLAZA");
		realty5.setPublishedDate(LocalDateTime.now());
		realty5.setUser(userbilge);
		realty5.setStatus(RealtyStatus.ACTIVE);
		realty5.setType(RealtyType.WORKPLACE);
		realty5.setOption(RealtyOption.FORSALE);
		realty5.setProvince("İstanbul");
		realty5.setDistrict("Beşiktaş");*/
		
		/*Realty realty6 = factory.getRealty();
		
		realty6.setNo(7465312);
		realty6.setTitle("Sancaktepe Türkeli Caddesinde 408 m² Satılık Arsa");
		realty6.setPublishedDate(LocalDateTime.now());
		realty6.setUser(userfisun);
		realty6.setStatus(RealtyStatus.ACTIVE);
		realty6.setType(RealtyType.LAND);
		realty6.setOption(RealtyOption.FORSALE);
		realty6.setProvince("İstanbul");
		realty6.setDistrict("Sancaktepe");*/
		
		Realty realty7 = factory.getRealty();
		
		realty7.setNo(1673542);
		realty7.setTitle("GÖZTEPE STAD YAKINI 150m² CADDE ÜZERİ KİRALIK DAİRE");
		realty7.setPublishedDate(LocalDateTime.now());
		realty7.setUser(userbilge);
		realty7.setStatus(RealtyStatus.ACTIVE);
		realty7.setType(RealtyType.HOUSE);
		realty7.setOption(RealtyOption.FORRENT);
		realty7.setProvince("İzmir");
		realty7.setDistrict("Göztepe");
		
		Realty realty8 = factory.getRealty();
		
		realty8.setNo(6351247);
		realty8.setTitle("İzmir Selçuk Cumhuriyet Mahallesinde Satılık 3+1 Daire");
		realty8.setPublishedDate(LocalDateTime.now());
		realty8.setUser(userfisun);
		realty8.setStatus(RealtyStatus.ACTIVE);
		realty8.setType(RealtyType.HOUSE);
		realty8.setOption(RealtyOption.FORSALE);
		realty8.setProvince("İzmir");
		realty8.setDistrict("Selçuk");
		
		/*Realty realty9 = factory.getRealty();
		
		realty9.setNo(5134762);
		realty9.setTitle("AKADEMİ'DEN SERENİTY PROJEMZDE 10.KAT KUZEY-DOĞU CEPHE LÜX 4,5+1");
		realty9.setPublishedDate(LocalDateTime.now());
		realty9.setUser(userfisun);
		realty9.setStatus(RealtyStatus.PASSIVE);
		realty9.setType(RealtyType.HOUSE);
		realty9.setOption(RealtyOption.FORSALE);
		realty9.setProvince("Ankara");
		realty9.setDistrict("Keçiören");*/
		
		/*Realty realty10 = factory.getRealty();
		
		realty10.setNo(6351427);
		realty10.setTitle("TUR EMLAK TANYELİ SOKAK KİRALIK DAİRE");
		realty10.setPublishedDate(LocalDateTime.now());
		realty10.setUser(userbilge);
		realty10.setStatus(RealtyStatus.PASSIVE);
		realty10.setType(RealtyType.HOUSE);
		realty10.setOption(RealtyOption.FORRENT);
		realty10.setProvince("Ankara");
		realty10.setDistrict("Çankaya");*/
		
		Realty realty11 = factory.getRealty();
		
		realty11.setNo(7436512);
		realty11.setTitle("FULL DENİZ MANZARALI 2+1 DAİRE FIRSATI");
		realty11.setPublishedDate(LocalDateTime.now());
		realty11.setUser(usercem);
		realty11.setStatus(RealtyStatus.ACTIVE);
		realty11.setType(RealtyType.HOUSE);
		realty11.setOption(RealtyOption.FORSALE);
		realty11.setProvince("İzmir");
		realty11.setDistrict("Güzelbahçe");
		
		Realty realty12 = factory.getRealty();
		
		realty12.setNo(5713426);
		realty12.setTitle("Çeşme Merkezde Çarşıya Çok Yakın Yeni Binada Balkonlu Bahçeli 2+1 Satılık Daire");
		realty12.setPublishedDate(LocalDateTime.now());
		realty12.setUser(usercem);
		realty12.setStatus(RealtyStatus.ACTIVE);
		realty12.setType(RealtyType.HOUSE);
		realty12.setOption(RealtyOption.FORSALE);
		realty12.setProvince("İzmir");
		realty12.setDistrict("Çeşme");
		
		Realty realty13 = factory.getRealty();
		
		realty13.setNo(1463275);
		realty13.setTitle("SATILIK TARLA URLA' DA DENİZ VE DOĞA MANZARALI KUPON LOKASYONDA");
		realty13.setPublishedDate(LocalDateTime.now());
		realty13.setUser(usercem);
		realty13.setStatus(RealtyStatus.ACTIVE);
		realty13.setType(RealtyType.LAND);
		realty13.setOption(RealtyOption.FORSALE);
		realty13.setProvince("İzmir");
		realty13.setDistrict("Urla");
		
		Realty realty14 = factory.getRealty();
		
		realty14.setNo(2674513);
		realty14.setTitle("Karşıyaka MAVİŞEHİRDE (4Katlı) KURUMSALA Kiralık VİLLA&BİNA");
		realty14.setPublishedDate(LocalDateTime.now());
		realty14.setUser(usercem);
		realty14.setStatus(RealtyStatus.PASSIVE);
		realty14.setType(RealtyType.WORKPLACE);
		realty14.setOption(RealtyOption.FORRENT);
		realty14.setProvince("İzmir");
		realty14.setDistrict("Karşıyaka");
		
Realty realty15 = factory.getRealty();
		
		realty15.setNo(5216734);
		realty15.setTitle("SARIYER TARABYA SANATÇILAR SİT. 155 m2 3+1 YENİLENMİŞ BAKIMLI ARA DUBLEKS");
		realty15.setPublishedDate(LocalDateTime.now());
		realty15.setUser(usercem);
		realty15.setStatus(RealtyStatus.ACTIVE);
		realty15.setType(RealtyType.HOUSE);
		realty15.setOption(RealtyOption.FORSALE);
		realty15.setProvince("İstanbul");
		realty15.setDistrict("Tarabya");
		
		Realty realty16 = factory.getRealty();
		
		realty16.setNo(1563427);
		realty16.setTitle("KIŞ BAHÇELİ ŞIK TASARIMIYLA BAHÇE KAT DAİRE FIRSATI !!!");
		realty16.setPublishedDate(LocalDateTime.now());
		realty16.setUser(usercem);
		realty16.setStatus(RealtyStatus.ACTIVE);
		realty16.setType(RealtyType.HOUSE);
		realty16.setOption(RealtyOption.FORSALE);
		realty16.setProvince("İstanbul");
		realty16.setDistrict("Esenyurt");
		
		Realty realty17 = factory.getRealty();
		
		realty17.setNo(3651274);
		realty17.setTitle("KOMİSYONSUZ LÜKS ULTRA GENİŞ KAÇIRILMAYACAK DÜZ GİRİŞ DAİRE !!!");
		realty17.setPublishedDate(LocalDateTime.now());
		realty17.setUser(usercem);
		realty17.setStatus(RealtyStatus.ACTIVE);
		realty17.setType(RealtyType.HOUSE);
		realty17.setOption(RealtyOption.FORSALE);
		realty17.setProvince("İstanbul");
		realty17.setDistrict("Esenyurt");
		
		Realty realty18 = factory.getRealty();
		
		realty18.setNo(4176523);
		realty18.setTitle("BEYLİKDÜZÜDE MARMARA GRUP FARKINI YAŞAMADAN DAİRE ALMAYINIZ");
		realty18.setPublishedDate(LocalDateTime.now());
		realty18.setUser(usercem);
		realty18.setStatus(RealtyStatus.ACTIVE);
		realty18.setType(RealtyType.HOUSE);
		realty18.setOption(RealtyOption.FORSALE);
		realty18.setProvince("İstanbul");
		realty18.setDistrict("Beylikdüzü");
		
		Realty realty19 = factory.getRealty();
		
		realty19.setNo(6735214);
		realty19.setTitle("GOZTEPE MARMARAY CADDE YAKIN 3+1 KOMBİLİ SIFIR BOŞ");
		realty19.setPublishedDate(LocalDateTime.now());
		realty19.setUser(usercem);
		realty19.setStatus(RealtyStatus.ACTIVE);
		realty19.setType(RealtyType.HOUSE);
		realty19.setOption(RealtyOption.FORSALE);
		realty19.setProvince("İstanbul");
		realty19.setDistrict("Göztepe");
		
		Realty realty20 = factory.getRealty();
		
		realty20.setNo(2531746);
		realty20.setTitle("ARNAVUTKÖY TAŞOLUK HAVALİMANI YOLU UZERİ SATILIK ARSA");
		realty20.setPublishedDate(LocalDateTime.now());
		realty20.setUser(usercem);
		realty20.setStatus(RealtyStatus.ACTIVE);
		realty20.setType(RealtyType.LAND);
		realty20.setOption(RealtyOption.FORSALE);
		realty20.setProvince("İstanbul");
		realty20.setDistrict("Arnavutköy");
		
		Realty realty21 = factory.getRealty();
		
		realty21.setNo(7154623);
		realty21.setTitle("Tuzla Orhanlı'da Etrafı Çevrili Boş Arsa");
		realty21.setPublishedDate(LocalDateTime.now());
		realty21.setUser(usercem);
		realty21.setStatus(RealtyStatus.ACTIVE);
		realty21.setType(RealtyType.LAND);
		realty21.setOption(RealtyOption.FORRENT);
		realty21.setProvince("İstanbul");
		realty21.setDistrict("Tuzla");
		
		Realty realty22 = factory.getRealty();
		
		realty22.setNo(4721563);
		realty22.setTitle("SİLİVRİ BALABAN ( ÇANTA-MİMARSİNAN)204 m2 Kat ittifak Tapulu....");
		realty22.setPublishedDate(LocalDateTime.now());
		realty22.setUser(usercem);
		realty22.setStatus(RealtyStatus.ACTIVE);
		realty22.setType(RealtyType.LAND);
		realty22.setOption(RealtyOption.FORSALE);
		realty22.setProvince("İstanbul");
		realty22.setDistrict("Silivri");
		
		Realty realty23 = factory.getRealty();
		
		realty23.setNo(6347251);
		realty23.setTitle("MUTLU EGE MİLLET BAHÇESİ YAKINI 4+1 DUBLEKS DOĞU-GÜNEY CEPHE BAKIMLI DAİRE");
		realty23.setPublishedDate(LocalDateTime.now());
		realty23.setUser(usercem);
		realty23.setStatus(RealtyStatus.ACTIVE);
		realty23.setType(RealtyType.HOUSE);
		realty23.setOption(RealtyOption.FORSALE);
		realty23.setProvince("Ankara");
		realty23.setDistrict("Mamak");
		
		Realty realty24 = factory.getRealty();
		
		realty24.setNo(1352764);
		realty24.setTitle("BİRİNCİ SINIF KALİTELİ LÜKS TERAS BALKONLU 3+1 ÖRNEK DAİRE");
		realty24.setPublishedDate(LocalDateTime.now());
		realty24.setUser(usercem);
		realty24.setStatus(RealtyStatus.ACTIVE);
		realty24.setType(RealtyType.HOUSE);
		realty24.setOption(RealtyOption.FORSALE);
		realty24.setProvince("Ankara");
		realty24.setDistrict("Mamak");
		
		Realty realty25 = factory.getRealty();
		
		realty25.setNo(4163257);
		realty25.setTitle("SIHIYE KIZILAY UYGUN FİYAT EŞYALI SATILIK");
		realty25.setPublishedDate(LocalDateTime.now());
		realty25.setUser(usercem);
		realty25.setStatus(RealtyStatus.ACTIVE);
		realty25.setType(RealtyType.HOUSE);
		realty25.setOption(RealtyOption.FORSALE);
		realty25.setProvince("Ankara");
		realty25.setDistrict("Çankaya");
		
		Realty realty26 = factory.getRealty();
		
		realty26.setNo(4163257);
		realty26.setTitle("TURAN GÜNEŞ BULV. YILDIZ KULE YANI SATILIK BÜYÜK TİP 1+1 DAİRE");
		realty26.setPublishedDate(LocalDateTime.now());
		realty26.setUser(usercem);
		realty26.setStatus(RealtyStatus.ACTIVE);
		realty26.setType(RealtyType.HOUSE);
		realty26.setOption(RealtyOption.FORSALE);
		realty26.setProvince("Ankara");
		realty26.setDistrict("Çankaya");
		
		Realty realty27 = factory.getRealty();
		
		realty27.setNo(2173456);
		realty27.setTitle("UĞUR YALÇINDAN AHİMESUT MAHALLESİNDE AYYILDIZ PROJEYE YAKIN DAİRE");
		realty27.setPublishedDate(LocalDateTime.now());
		realty27.setUser(usercem);
		realty27.setStatus(RealtyStatus.ACTIVE);
		realty27.setType(RealtyType.HOUSE);
		realty27.setOption(RealtyOption.FORSALE);
		realty27.setProvince("Ankara");
		realty27.setDistrict("Etimesgut");
		
		Realty realty28 = factory.getRealty();
		
		realty28.setNo(7453216);
		realty28.setTitle("BİRLİK PAZAR YERİ YAKINI,4+1,150 M2,KOMBİLİ,Y.GİRİŞ2 BANYOLU");
		realty28.setPublishedDate(LocalDateTime.now());
		realty28.setUser(usercem);
		realty28.setStatus(RealtyStatus.ACTIVE);
		realty28.setType(RealtyType.HOUSE);
		realty28.setOption(RealtyOption.FORSALE);
		realty28.setProvince("Ankara");
		realty28.setDistrict("Çankaya");
		
		Realty realty29 = factory.getRealty();
		
		realty29.setNo(4231657);
		realty29.setTitle("ACİL SATILIK 3KATLI BİNA ANKARA SİTELERDE COK UYGUN FİYAT");
		realty29.setPublishedDate(LocalDateTime.now());
		realty29.setUser(usercem);
		realty29.setStatus(RealtyStatus.ACTIVE);
		realty29.setType(RealtyType.HOUSE);
		realty29.setOption(RealtyOption.FORSALE);
		realty29.setProvince("Ankara");
		realty29.setDistrict("Altındağ");
		
		Realty realty30 = factory.getRealty();
		
		realty30.setNo(1237654);
		realty30.setTitle("Çankaya Şehit Ersan'da 280 m2 Prestij Asansörlü Kiralık Ofis");
		realty30.setPublishedDate(LocalDateTime.now());
		realty30.setUser(usercem);
		realty30.setStatus(RealtyStatus.ACTIVE);
		realty30.setType(RealtyType.WORKPLACE);
		realty30.setOption(RealtyOption.FORRENT);
		realty30.setProvince("Ankara");
		realty30.setDistrict("Çankaya");
		
		Realty realty31 = factory.getRealty();
		
		realty31.setNo(5632714);
		realty31.setTitle("SEĞMENLER CEMAL GÜRSEL CADDESİ ÜZERİNDE 45 M² + 45 M² DEPO KİRALIK İŞ YERİ");
		realty31.setPublishedDate(LocalDateTime.now());
		realty31.setUser(usercem);
		realty31.setStatus(RealtyStatus.ACTIVE);
		realty31.setType(RealtyType.WORKPLACE);
		realty31.setOption(RealtyOption.FORRENT);
		realty31.setProvince("Ankara");
		realty31.setDistrict("Gölbaşı");
		
		Realty realty32 = factory.getRealty();
		
		realty32.setNo(1736524);
		realty32.setTitle("ANKARA SİNCAN CADDEDE 3000TL KİRACILI 145M2 SATILIK DÜKKAN");
		realty32.setPublishedDate(LocalDateTime.now());
		realty32.setUser(usercem);
		realty32.setStatus(RealtyStatus.ACTIVE);
		realty32.setType(RealtyType.WORKPLACE);
		realty32.setOption(RealtyOption.FORSALE);
		realty32.setProvince("Ankara");
		realty32.setDistrict("Sincan");
		
		Realty realty33 = factory.getRealty();
		
		realty33.setNo(6473521);
		realty33.setTitle("Çankaya Hanımeli Sokak'ta 1+1+Antre+Mutfak+Wc +Ön Cephe Otoparklı +Asansörlü Satılık Büro");
		realty33.setPublishedDate(LocalDateTime.now());
		realty33.setUser(usercem);
		realty33.setStatus(RealtyStatus.ACTIVE);
		realty33.setType(RealtyType.WORKPLACE);
		realty33.setOption(RealtyOption.FORSALE);
		realty33.setProvince("Ankara");
		realty33.setDistrict("Çankaya");

		Realty realty34 = factory.getRealty();
		
		realty34.setNo(6473521);
		realty34.setTitle("ŞİRİNYER CADDE ÜZERİ SATILIK DÜKKAN");
		realty34.setPublishedDate(LocalDateTime.now());
		realty34.setUser(usercem);
		realty34.setStatus(RealtyStatus.ACTIVE);
		realty34.setType(RealtyType.WORKPLACE);
		realty34.setOption(RealtyOption.FORSALE);
		realty34.setProvince("İzmir");
		realty34.setDistrict("Buca");
		
		Realty realty35 = factory.getRealty();
		
		realty35.setNo(2746531);
		realty35.setTitle("ÖĞRETMEN EMLAKTAN HASTANE KARŞISI KÖŞE ÇİFT CEPHE BATARLI DÜKKAN");
		realty35.setPublishedDate(LocalDateTime.now());
		realty35.setUser(usercem);
		realty35.setStatus(RealtyStatus.ACTIVE);
		realty35.setType(RealtyType.WORKPLACE);
		realty35.setOption(RealtyOption.FORSALE);
		realty35.setProvince("İzmir");
		realty35.setDistrict("Menderes");
		
		Realty realty36 = factory.getRealty();
		
		realty36.setNo(3675421);
		realty36.setTitle("##MÜKEMMEL KONUMDA SIFIR AYARINDA DAİRE##");
		realty36.setPublishedDate(LocalDateTime.now());
		realty36.setUser(usercem);
		realty36.setStatus(RealtyStatus.ACTIVE);
		realty36.setType(RealtyType.HOUSE);
		realty36.setOption(RealtyOption.FORSALE);
		realty36.setProvince("İzmir");
		realty36.setDistrict("Menderes");
		
		Realty realty37 = factory.getRealty();
		
		realty37.setNo(7461352);
		realty37.setTitle("KARABAĞLAR ESENLİK MAHALLESİ SATILIK ARSA");
		realty37.setPublishedDate(LocalDateTime.now());
		realty37.setUser(usercem);
		realty37.setStatus(RealtyStatus.ACTIVE);
		realty37.setType(RealtyType.LAND);
		realty37.setOption(RealtyOption.FORSALE);
		realty37.setProvince("İzmir");
		realty37.setDistrict("Karabağlar");
		
		Realty realty38 = factory.getRealty();
		
		realty38.setNo(4675321);
		realty38.setTitle("KARABAĞLAR ESENLİK MAHALLESİ SATILIK ARSA");
		realty38.setPublishedDate(LocalDateTime.now());
		realty38.setUser(usercem);
		realty38.setStatus(RealtyStatus.ACTIVE);
		realty38.setType(RealtyType.LAND);
		realty38.setOption(RealtyOption.FORSALE);
		realty38.setProvince("İzmir");
		realty38.setDistrict("Karabağlar");
		
		Realty realty39 = factory.getRealty();
		
		realty39.setNo(3745612);
		realty39.setTitle("GÖZTEPE STAD YAKINI 150m² CADDE ÜZERİ KİRALIK DAİRE");
		realty39.setPublishedDate(LocalDateTime.now());
		realty39.setUser(usercem);
		realty39.setStatus(RealtyStatus.ACTIVE);
		realty39.setType(RealtyType.HOUSE);
		realty39.setOption(RealtyOption.FORRENT);
		realty39.setProvince("İzmir");
		realty39.setDistrict("Karabağlar");
		
		
		
		
		
		
		
		//UserService object
		UserService userService = UserService.getUserService();
		
		//Create userList, userahmet, userayse, usermehmet için şifre ve emailden en az biri hatalı olduğu için
		//onları listeye eklemedi ve hata mesajı yayınladı
		userService.createUser(userbilge);
		userService.createUser(userfisun);
		userService.createUser(usercem);
		/*userService.createUser(userahmet);
		userService.createUser(userayse);
		userService.createUser(usermehmet);*/
		
		//Print all users
		//userService.printAllUser();
		
		
		//RealtyService object
		RealtyService realtyService = RealtyService.getRealtyService();
		
		//create realtyList, userbilge ve userfisun için konut dışı emlaklarda uyarı yazdrıdı. Ayrıca 4. ilanlarında
		//da uyarı yazdırdı.
		realtyService.createRealty(realty1);
		realtyService.createRealty(realty2);
		realtyService.createRealty(realty3);
		realtyService.createRealty(realty4);
		//realtyService.createRealty(realty5);
		//realtyService.createRealty(realty6);
		realtyService.createRealty(realty7);
		realtyService.createRealty(realty8);
		//realtyService.createRealty(realty9);
		//realtyService.createRealty(realty10);
		realtyService.createRealty(realty11);
		realtyService.createRealty(realty12);
		realtyService.createRealty(realty13);
		realtyService.createRealty(realty14);
		realtyService.createRealty(realty15);
		realtyService.createRealty(realty16);
		realtyService.createRealty(realty17);
		realtyService.createRealty(realty18);
		realtyService.createRealty(realty19);
		realtyService.createRealty(realty20);
		realtyService.createRealty(realty21);
		realtyService.createRealty(realty22);
		realtyService.createRealty(realty23);
		realtyService.createRealty(realty24);
		realtyService.createRealty(realty25);
		realtyService.createRealty(realty26);
		realtyService.createRealty(realty27);
		realtyService.createRealty(realty28);
		realtyService.createRealty(realty29);
		realtyService.createRealty(realty30);
		realtyService.createRealty(realty31);
		realtyService.createRealty(realty32);
		realtyService.createRealty(realty33);
		realtyService.createRealty(realty34);
		realtyService.createRealty(realty35);
		realtyService.createRealty(realty36);
		realtyService.createRealty(realty37);
		realtyService.createRealty(realty38);
		realtyService.createRealty(realty39);
		
		//Print realty by user name 
		/*System.out.println(realtyService.getAllByUserName(userbilge));
		System.out.println(realtyService.getAllByUserName(userfisun));
		System.out.println(realtyService.getAllByUserName(usercem));*/
		
		//Print active realty by user name
		/*System.out.println(realtyService.getActiveRealtyByUserName(userbilge));
		System.out.println(realtyService.getActiveRealtyByUserName(userfisun));
		System.out.println(realtyService.getActiveRealtyByUserName(usercem));*/
		
		//Number of realities by province
		/*System.out.println(realtyService.getNumberByProvince("İstanbul"));
		System.out.println(realtyService.getNumberByProvince("Ankara"));
		System.out.println(realtyService.getNumberByProvince("İzmir"));*/
	
		//Number of for sale houses by province and district
		/*System.out.println(realtyService.getNumberOfForSaleHouseByProvince("İstanbul"));
		System.out.println(realtyService.getNumberOfForSaleHouseByProvince("Ankara"));
		System.out.println(realtyService.getNumberOfForSaleHouseByProvince("İzmir"));*/
		
		//Searching by Province and District. İlan yoksa bir şey dönmüyor
		/*realtyService.getAllByProvinceAndDistrict("İstanbul", "Beşiktaş");
		realtyService.getAllByProvinceAndDistrict("Ankara", "Keçiören");
		realtyService.getAllByProvinceAndDistrict("İzmir", "Karşıyaka");
		realtyService.getAllByProvinceAndDistrict("Bursa", "Yıldırım");*/
		
		//Saving realties and printing them
		/*List<Realty> userbilgeSavedRealties = new ArrayList<>();
		List<Realty> usercemSavedRealties = new ArrayList<>();
		List<Realty> userfisunSavedRealties = new ArrayList<>();
			
		userbilgeSavedRealties.add(realty2);
		userbilgeSavedRealties.add(realty4);
		userbilgeSavedRealties.add(realty8);
		userbilgeSavedRealties.add(realty12);
		userbilge.setSavedRealtyList(userbilgeSavedRealties);
				
		userfisunSavedRealties.add(realty1);
		userfisunSavedRealties.add(realty3);
		userfisunSavedRealties.add(realty11);
		userfisun.setSavedRealtyList(userfisunSavedRealties);
						
		usercemSavedRealties.add(realty7);
		usercemSavedRealties.add(realty8);
		usercemSavedRealties.add(realty1);
		usercemSavedRealties.add(realty4);
		usercem.setSavedRealtyList(usercemSavedRealties);
				
		System.out.println(userbilge.getSavedRealtyList());
		System.out.println(userfisun.getSavedRealtyList());
		System.out.println(usercem.getSavedRealtyList());*/
		
		
		//Showcase Lists
		Realty [] istanbulShowcase = new Realty[10];
		Realty [] ankaraShowcase = new Realty[10];
		Realty [] izmirShowcase = new Realty[10];
		
		//10.ilandan sonra hata verir
		istanbulShowcase[0] = realty1;
		istanbulShowcase[1] = realty2;
		istanbulShowcase[2] = realty3;
		istanbulShowcase[3] = realty15;
		istanbulShowcase[4] = realty16;
		istanbulShowcase[5] = realty17;
		istanbulShowcase[6] = realty18;
		istanbulShowcase[7] = realty19;
		istanbulShowcase[8] = realty20;
		istanbulShowcase[9] = realty21;
		//istanbulShowcase[10] = realty22;
		
		ankaraShowcase[0] = realty4;
		ankaraShowcase[1] = realty23;
		ankaraShowcase[2] = realty24;
		ankaraShowcase[3] = realty25;
		ankaraShowcase[4] = realty26;
		ankaraShowcase[5] = realty27;
		ankaraShowcase[6] = realty28;
		ankaraShowcase[7] = realty29;
		ankaraShowcase[8] = realty30;
		ankaraShowcase[9] = realty31;
		//ankaraShowcase[10] = realty32;
		
		izmirShowcase[0] = realty7;
		izmirShowcase[1] = realty8;
		izmirShowcase[2] = realty11;
		izmirShowcase[3] = realty12;
		izmirShowcase[4] = realty13;
		izmirShowcase[5] = realty14;
		izmirShowcase[6] = realty34;
		izmirShowcase[7] = realty35;
		izmirShowcase[8] = realty36;
		izmirShowcase[9] = realty37;
		//izmirShowcase[10] = realty38;
		
		/*for (Realty realty : istanbulShowcase)
		{
			System.out.println(realty);
		}*/
		
		/*for (Realty realty : ankaraShowcase)
		{
			System.out.println(realty);
		}*/
		
		/*for (Realty realty : izmirShowcase)
		{
			System.out.println(realty);
		}*/
		
		
		
				
		
		
		
		
		
		
		
		
		
		
		

	}

}
